---
#####################################
# Host maintenance
#####################################
- name: Perform machine maintenance
  hosts: all
  become: true
  vars_files:
    - defaults/main.yml

  tasks:
   - name: Update all packages
     yum:
        name: '*'
        state: latest
